# version: '3.8'  # Updated version for compatibility and features

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.33.0
    ports:
      - 9090:9090
    volumes:
      - ./deploy/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - monitoring
    restart: unless-stopped # Ensures container will self recover by restarting unless manually stopped

  grafana:
    image: grafana/grafana-oss:8.3.4
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deploy/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped # Ensures container will self recover by restrating unless manually stopped

  storage_api:
    build:
      context: .  # Directory containing the Dockerfile. Make sure to run DOCKER COMPOSE UP from here
    container_name: storage_api
    environment:
      - FLASK_APP=storage_api
      - FLASK_ENV=production
    ports:
      - 5000:5000  # Expose the Flask app to the host
    networks:
      - monitoring
    restart: unless-stopped # Ensures container will self recover by restrating unless manually stopped

networks:
  monitoring:
    driver: bridge
