apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
  labels:
    app: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
      - name: storage-api
        image: justinvannoort/storage-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "storage_api"
        - name: FLASK_ENV
          value: "production"